[2023-09-19 07:19:40,950] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/urls.py changed, reloading.
[2023-09-19 07:19:41,399] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:20:01,021] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 07:20:01,466] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:20:03,550] WARNING [django.request:241] [none] Method Not Allowed: /auth/logout/
[2023-09-19 07:20:18,348] ERROR [django.request:241] [none] Internal Server Error: /auth/logout/
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'employee_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py", line 120, in post
    employee_id = request.employee_id
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'employee_id'
[2023-09-19 07:23:35,288] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 07:23:35,741] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:25:14,554] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 07:25:15,006] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:25:47,839] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:25:48,294] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:25:58,628] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:25:59,051] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:26:00,342] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:26:00,788] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:26:08,030] ERROR [employee.views:101] [none] Exception ("'int' object has no attribute 'is_logged_in'",)
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/task_management/employee/views.py", line 66, in get
    print(request.login.is_logged_in,"LOGINNNNNNNNNNNSSSSSSSSSSS")
AttributeError: 'int' object has no attribute 'is_logged_in'
[2023-09-19 07:26:08,031] ERROR [django.request:241] [none] Internal Server Error: /employee/task/creation/
[2023-09-19 07:26:27,541] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:26:27,965] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:27:08,956] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:27:09,382] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:27:10,687] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:27:11,122] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:27:18,445] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:27:18,873] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:27:20,159] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:27:20,607] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:27:40,380] ERROR [employee.views:101] [none] Exception ("'int' object has no attribute 'login_user'",)
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/task_management/employee/views.py", line 67, in get
    print(employee_id.login_user.is_logged_in,"employee_idemployee_id")
AttributeError: 'int' object has no attribute 'login_user'
[2023-09-19 07:27:40,380] ERROR [django.request:241] [none] Internal Server Error: /employee/task/creation/
[2023-09-19 07:28:07,658] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:08,122] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:28:12,467] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:12,879] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:28:37,558] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:38,016] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:28:39,323] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:39,732] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:28:42,981] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:43,447] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:28:45,794] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:46,237] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:28:47,523] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:28:47,939] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:29:26,777] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:29:27,193] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:29:31,497] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:29:31,907] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:29:40,244] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:29:40,677] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:29:42,012] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:29:42,446] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:29:43,741] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/employee/views.py changed, reloading.
[2023-09-19 07:29:44,208] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 07:38:52,996] ERROR [employee.views:101] [none] Exception ("'Request' object has no attribute 'login'",)
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/task_management/employee/views.py", line 66, in get
    print(request.login,"LOGINNNNNNNNNNNSSSSSSSSSSS")
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'login'
[2023-09-19 07:38:53,019] ERROR [django.request:241] [none] Internal Server Error: /employee/task/creation/
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/renderers.py", line 553, in get_raw_data_form
    serializer = view.get_serializer()
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'TaskCreation' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[2023-09-19 08:05:39,588] WARNING [django.request:241] [none] Not Found: /admin/core/billingreceiptnumber/1/change/
[2023-09-19 08:05:52,813] ERROR [employee.views:101] [none] Exception ("'Request' object has no attribute 'login'",)
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/task_management/employee/views.py", line 66, in get
    print(request.login,"LOGINNNNNNNNNNNSSSSSSSSSSS")
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'login'
[2023-09-19 08:05:52,833] ERROR [django.request:241] [none] Internal Server Error: /employee/task/creation/
Traceback (most recent call last):
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/renderers.py", line 553, in get_raw_data_form
    serializer = view.get_serializer()
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/emedhub/ReactProject/new_project/env/lib/python3.10/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'TaskCreation' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
[2023-09-19 10:42:00,060] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 10:42:00,800] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 10:42:02,215] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 10:42:02,643] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 10:42:20,221] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 10:42:20,664] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 10:42:28,058] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 10:42:28,505] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
[2023-09-19 10:42:30,806] INFO [django.utils.autoreload:266] [none] /home/emedhub/ReactProject/new_project/task_management/authentication/views/login_authentication.py changed, reloading.
[2023-09-19 10:42:31,238] INFO [django.utils.autoreload:668] [none] Watching for file changes with StatReloader
